# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_auto_20160521_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='details',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='program',
            field=models.CharField(max_length=100),
        ),
    ]
